# Generated by Django 5.2.3 on 2025-06-27 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('relatorio', 'Gerou relatório'), ('visualizou', 'Visualizou CAR'), ('cpf', 'Consultou CPF/CNPJ'), ('membro', 'Adicionou membro')], max_length=20)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
